### ISSUE TITLE
Netbox

### ISSUE THREAD

**Issue by xanderClaessens** [vives-project-xp/UpgradeVerlichtingsysteem#82]
We moeten kijken of netbox hier kan gebruikt worden

**Comment by xanderClaessens** [comment]
Elias en Robbe hebben Proxmox opgezet.

**Comment by xanderClaessens** [comment]
Ik heb Ubuntu opgezet en netbox op gezet.

**Comment by xanderClaessens** [comment]
Ik ben heb een api token aan netbox toegevoegd voor de verbinding met proxmox.

**Comment by xanderClaessens** [comment]
Opzoeken hoe proxmox verbinden met netbox, IPAM? Proxbox? Proxmox SDN? Wat zijn dit allemaal en is dit nodig?

**Comment by RobbeYT** [comment]
Het is niet gemakkelijk om dit te verbinden
